DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  -- Account details --
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` CHAR(255) NOT NULL,
  -- Extra account info --
  `user_level` BOOLEAN NOT NULL DEFAULT 0,
  `banned` BOOLEAN NOT NULL DEFAULT 0,
  `lab_pass` BOOLEAN NOT NULL DEFAULT 0,
  `lab_pass_days` SMALLINT(4) NOT NULL DEFAULT 0 CHECK (`lab_pass_days` BETWEEN 0 AND 9999),
  `credits` MEDIUMINT(6) NOT NULL DEFAULT 0 CHECK (`credits` BETWEEN 0 AND 999999),
  `ticket` BOOLEAN NOT NULL DEFAULT 1,
  -- Stats --
  `rounds` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `kills` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `deaths` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `wins` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `losses` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `spinners`;
CREATE TABLE `spinners` (
  -- Spinner info --
  `id` INT(10) UNSIGNED NOT NULL,
  `uniqueItemId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `itemId` TINYINT(3) UNSIGNED NOT NULL,
  `selected` BOOLEAN NOT NULL DEFAULT 0,
  -- Spinner inner color --
  `redInner` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 255,
  `greenInner` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  `blueInner` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  -- Spinner outer color --
  `redOuter` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 255,
  `greenOuter` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  `blueOuter` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  PRIMARY KEY (`uniqueItemId`),
  CONSTRAINT `spinners_ibfk_1` FOREIGN KEY (`id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `pets`;
CREATE TABLE `pets` (
  -- Pet info --
  `id` INT(10) UNSIGNED NOT NULL,
  `uniqueItemId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `itemId` TINYINT(3) UNSIGNED NOT NULL,
  `selected` BOOLEAN NOT NULL DEFAULT 0,
  -- Pet inner color --
  `redInner` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 255,
  `greenInner` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  `blueInner` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  -- Pet outer color --
  `redOuter` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 255,
  `greenOuter` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  `blueOuter` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  PRIMARY KEY (`uniqueItemId`),
  CONSTRAINT `pets_ibfk_1` FOREIGN KEY (`id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `reports`;
CREATE TABLE `reports` (
  -- Report account details --
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `reporter_username` VARCHAR(20) NOT NULL,
  `reported_username` VARCHAR(20) NOT NULL,
  `reported_ip` VARCHAR(15) NOT NULL,
  -- Report --
  `msg` CHAR(250) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
